CREATE TABLE visitor_log
(
    v_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 기록 고유 번호
    v_writer_id VARCHAR(50) NOT NULL,                                -- 방문한 사람 아이디 (회원테이블 연동)
    v_owner_id  VARCHAR(50) NOT NULL,                                -- 홈피 주인 아이디
    v_emoji     INT       DEFAULT 1,                                 -- 발도장 모양 (1:기본, 2:슬픔 등)
    v_date      TIMESTAMP DEFAULT CURRENT_TIMESTAMP                  -- 언제 다녀갔는지 (자동입력)
);

-- 1. 첫 번째 방문자
INSERT INTO visitor_log (v_writer_id, v_owner_id, v_emoji)
VALUES ('MiniMe123', 'DongMin', 1);

-- 2. 두 번째 방문자
INSERT INTO visitor_log (v_writer_id, v_owner_id, v_emoji)
VALUES ('HappyUser', 'DongMin', 2);

-- 3. 세 번째 방문자
INSERT INTO visitor_log (v_writer_id, v_owner_id, v_emoji)
VALUES ('CyWorldFan', 'DongMin', 5);

SELECT * FROM visitor_log ORDER BY v_date DESC;